import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { NextIntlClientProvider } from "next-intl";

import { ConsentManagerProvider } from "@/src/lib/consent-manager/provider";

import { scriptsTransformer } from '@/src/data-transformers/scripts-transformer';

import { rootData } from "@/src/script-data";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const scripts = scriptsTransformer(rootData.data.site.content.scripts);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider>
          <ConsentManagerProvider scripts={scripts}>
            {children}
          </ConsentManagerProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
